name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['18.x', '20.x']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Change directory to 'be' and run tests
      run: |
        cd be/
        npm install   # Install dependencies, including Jest
        npm test      # Run tests using Jest

    - name: Upload test coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: be/coverage   # Adjust path to Jest coverage report if needed
